version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: talent-track-server
    container_name: talent-track-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:80"
